<?php

use Illuminate\Support\Str;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

$categoryId = Str::uuid()->toString();

DB::table('categories')->insertOrIgnore([
    'id' => $categoryId,
    'name' => 'Official Announcements',
    'created_at' => Carbon::now(),
    'updated_at' => Carbon::now(),
]);

$posts = [
    // Previous 4
    [
        'id' => Str::uuid()->toString(),
        'category_id' => $categoryId,
        'title' => 'Minister calls for strengthening of state-run media',
        'excerpt' => 'Minister Neth Pheaktra called for the strengthening of state-run media (radio, television, digital apps) to improve national communication.',
        'content' => '<p>In August 2026, Minister Neth Pheaktra called for the strengthening of state-run media, including radio, television, digital apps, and PDF newspapers, to improve national communication and maintain national security and public order. He emphasized modernizing Cambodia\'s information system by expanding official websites to all 25 municipal and provincial information departments.</p>',
        'featured_image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Ministry_of_Information_%28Cambodia%29_logo.png/500px-Ministry_of_Information_%28Cambodia%29_logo.png',
        'published_at' => '2026-08-10 09:00:00',
        'status' => 'published',
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'id' => Str::uuid()->toString(),
        'category_id' => $categoryId,
        'title' => 'Ministry plans update of information and broadcasting legal framework',
        'excerpt' => 'Plans announced to update and harmonize Cambodia\'s legal framework for the information and broadcasting sector.',
        'content' => '<p>In July 2026, Minister Neth Pheaktra announced plans to update and harmonize Cambodia\'s legal framework for the information and broadcasting sector. This comprehensive reform includes strengthening oversight of digital content, influencers, and AI-generated material. The goal is to combat fake news, disinformation, and protect the dignity of citizens while adapting to rapid digital transformation.</p>',
        'featured_image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Ministry_of_Information_%28Cambodia%29_logo.png/500px-Ministry_of_Information_%28Cambodia%29_logo.png',
        'published_at' => '2026-07-15 14:30:00',
        'status' => 'published',
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'id' => Str::uuid()->toString(),
        'category_id' => $categoryId,
        'title' => 'Cambodia hosts the 20th Asia Media Summit (AMS 2025)',
        'excerpt' => 'Cambodia hosted the 20th Asia Media Summit, proposing the "Second Angkor Declaration" regarding AI in media.',
        'content' => '<p>Cambodia successfully hosted the 20th Asia Media Summit. During the summit, the Ministry of Information emphasized the country\'s leadership in regional cooperation against misinformation. Minister Pheaktra proposed the "Second Angkor Declaration" to specifically address the emerging challenges posed by AI-generated content and deepfakes across the ASEAN region.</p>',
        'featured_image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Ministry_of_Information_%28Cambodia%29_logo.png/500px-Ministry_of_Information_%28Cambodia%29_logo.png',
        'published_at' => '2025-05-12 10:00:00',
        'status' => 'published',
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'id' => Str::uuid()->toString(),
        'category_id' => $categoryId,
        'title' => '"Say No to Fake News" Campaign Launched Nationwide',
        'excerpt' => 'The government launches a nationwide campaign to combat misinformation and digital scams.',
        'content' => '<p>The government, acting through the Ministry of Information, has launched a nationwide "Say No to Fake News" campaign. The initiative aims to combat misinformation, fake news, and digital scams by promoting media literacy. The Ministry specifically called on Cambodian youth to act as "information protection agents" to help verify sources and stop the spread of false information on social media platforms.</p>',
        'featured_image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Ministry_of_Information_%28Cambodia%29_logo.png/500px-Ministry_of_Information_%28Cambodia%29_logo.png',
        'published_at' => '2026-03-20 08:45:00',
        'status' => 'published',
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    
    // 10 NEW Articles
    [
        'id' => Str::uuid()->toString(),
        'category_id' => $categoryId,
        'title' => 'Ministry announces international conference on cybercrime',
        'excerpt' => 'The Ministry of Information will host an international conference focusing on combating cybercrime and breaking digital criminal chains.',
        'content' => '<p>In August 2026, the Ministry of Information officially announced an upcoming international conference dedicated to combating cybercrime. The strategic aim of this conference is to foster regional collaboration to break the chain of digital criminal activity. The initiative will bring together cybersecurity experts, lawmakers, and media representatives to discuss modern solutions to digital threats.</p>',
        'featured_image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Ministry_of_Information_%28Cambodia%29_logo.png/500px-Ministry_of_Information_%28Cambodia%29_logo.png',
        'published_at' => '2026-08-05 10:15:00',
        'status' => 'published',
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'id' => Str::uuid()->toString(),
        'category_id' => $categoryId,
        'title' => 'Participation in 23rd ASEAN SOMRI Meeting',
        'excerpt' => 'The Ministry participated in the 23rd ASEAN Senior Officials Responsible for Information Meeting (SOMRI).',
        'content' => '<p>In June 2026, delegates from the Ministry of Information represented Cambodia at the 23rd ASEAN Senior Officials Responsible for Information Meeting (SOMRI). During the sessions, the Ministry actively supported multiple initiatives aimed at enhancing media literacy, ensuring information integrity, and fostering stronger communication channels between ASEAN member states.</p>',
        'featured_image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Ministry_of_Information_%28Cambodia%29_logo.png/500px-Ministry_of_Information_%28Cambodia%29_logo.png',
        'published_at' => '2026-06-22 14:00:00',
        'status' => 'published',
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'id' => Str::uuid()->toString(),
        'category_id' => $categoryId,
        'title' => 'Modernization of Media Governance for AI and Deepfakes',
        'excerpt' => 'New plans target AI-generated content and the activities of influencers to improve media accountability.',
        'content' => '<p>In July 2026, the Ministry unveiled its strategic plan to modernize media governance. A major focus of this reform is addressing the rapid rise of AI-generated content and deepfakes. The new legal framework will introduce stricter guidelines for digital influencers and content creators, aiming to elevate accountability and curb the spread of manipulated media.</p>',
        'featured_image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Ministry_of_Information_%28Cambodia%29_logo.png/500px-Ministry_of_Information_%28Cambodia%29_logo.png',
        'published_at' => '2026-07-28 11:30:00',
        'status' => 'published',
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'id' => Str::uuid()->toString(),
        'category_id' => $categoryId,
        'title' => 'Digital Modernization of 25 Provincial Information Departments',
        'excerpt' => 'The Ministry launched secure websites for all municipal and provincial Departments of Information.',
        'content' => '<p>In May 2026, the Ministry of Information rolled out a major digital modernization initiative. This project provides dedicated, highly secure websites for all 25 municipal and provincial Departments of Information across Cambodia. The initiative is designed to unify national data systems, streamline inter-departmental communication, and provide citizens with reliable local updates.</p>',
        'featured_image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Ministry_of_Information_%28Cambodia%29_logo.png/500px-Ministry_of_Information_%28Cambodia%29_logo.png',
        'published_at' => '2026-05-18 09:45:00',
        'status' => 'published',
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'id' => Str::uuid()->toString(),
        'category_id' => $categoryId,
        'title' => 'Phase Two of "Say No to Fake News" Campaign',
        'excerpt' => 'The second phase of the anti-misinformation campaign urges youth to be information protection agents.',
        'content' => '<p>Building on previous successes, the government launched the second phase of its nationwide "Say No to Fake News" campaign in May 2026. Minister Neth Pheaktra issued a public call urging the younger generation to step up as "information protection agents," taking an active role in identifying digital scams and preventing the proliferation of misinformation online.</p>',
        'featured_image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Ministry_of_Information_%28Cambodia%29_logo.png/500px-Ministry_of_Information_%28Cambodia%29_logo.png',
        'published_at' => '2026-05-02 10:00:00',
        'status' => 'published',
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'id' => Str::uuid()->toString(),
        'category_id' => $categoryId,
        'title' => 'Cambodia Recovers in World Press Freedom Index',
        'excerpt' => 'Reports show Cambodia\'s position in the RSF World Press Freedom Index shifted to 151st in 2026.',
        'content' => '<p>According to 2026 reports, Cambodia has seen a slight recovery in its press freedom standing. The nation\'s position in the Reporters Without Borders (RSF) World Press Freedom Index improved to 151st, up from the 161st position recorded in 2025. The Ministry noted this as a positive step reflecting ongoing reforms in the information sector.</p>',
        'featured_image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Ministry_of_Information_%28Cambodia%29_logo.png/500px-Ministry_of_Information_%28Cambodia%29_logo.png',
        'published_at' => '2026-04-10 13:20:00',
        'status' => 'published',
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'id' => Str::uuid()->toString(),
        'category_id' => $categoryId,
        'title' => 'Partnership with Ministry of Tourism to Counter Fake News',
        'excerpt' => 'A joint initiative was formed to promote authentic information about Cambodia and protect the tourism sector.',
        'content' => '<p>In late 2025, the Ministry of Information officially partnered with the Ministry of Tourism. This joint initiative focuses on promoting authentic, positive stories about Cambodia globally. A core objective is to rapidly counter negative narratives and fake news that could potentially harm the country\'s vital tourism industry and international reputation.</p>',
        'featured_image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Ministry_of_Information_%28Cambodia%29_logo.png/500px-Ministry_of_Information_%28Cambodia%29_logo.png',
        'published_at' => '2025-11-20 15:00:00',
        'status' => 'published',
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'id' => Str::uuid()->toString(),
        'category_id' => $categoryId,
        'title' => 'New Requirements for Journalism Qualifications Introduced',
        'excerpt' => 'The Ministry intensifies oversight with new standards for press card issuance.',
        'content' => '<p>Throughout 2025, the Ministry of Information intensified its regulatory oversight of the media sector. A major development was the introduction of strict new requirements for journalism qualifications. These new standards must be met prior to the issuance or renewal of official press cards, ensuring a higher standard of professionalism across the industry.</p>',
        'featured_image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Ministry_of_Information_%28Cambodia%29_logo.png/500px-Ministry_of_Information_%28Cambodia%29_logo.png',
        'published_at' => '2025-08-14 09:30:00',
        'status' => 'published',
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'id' => Str::uuid()->toString(),
        'category_id' => $categoryId,
        'title' => 'Sub-Decree No. 217 Designates Official State Media',
        'excerpt' => 'TVK, RNK, and AKP are formally designated as official state-media units under the Ministry.',
        'content' => '<p>In November 2025, the government issued Sub-Decree No. 217, which formally outlines the organization and functioning of the Ministry of Information. Crucially, this sub-decree officially designates the National Television of Cambodia (TVK), National Radio of Cambodia (RNK), and Agence Kampuchea Presse (AKP) as the primary state-media units operating under the Ministry\'s direct purview.</p>',
        'featured_image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Ministry_of_Information_%28Cambodia%29_logo.png/500px-Ministry_of_Information_%28Cambodia%29_logo.png',
        'published_at' => '2025-11-25 10:45:00',
        'status' => 'published',
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ],
    [
        'id' => Str::uuid()->toString(),
        'category_id' => $categoryId,
        'title' => '"Health Room for Officers" Officially Launched',
        'excerpt' => 'Minister Neth Pheaktra launches a new facility to support the well-being of ministry officials.',
        'content' => '<p>On May 15, 2024, the Ministry officially launched the "Health Room for Officers" at its headquarters. Directed by Minister Neth Pheaktra, this initiative aims to support the physical well-being of civil servants and reduce healthcare spending for ministry officials. The facility is equipped to provide basic medical consultations and emergency first aid.</p>',
        'featured_image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Ministry_of_Information_%28Cambodia%29_logo.png/500px-Ministry_of_Information_%28Cambodia%29_logo.png',
        'published_at' => '2024-05-15 11:00:00',
        'status' => 'published',
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now(),
    ]
];

DB::table('posts')->insert($posts);

echo "Successfully injected " . count($posts) . " news records.\n";
